export const newProducts = [
    {
        id: 'newproduct1',
        name: 'Áo Thun Gấu Nâu',
        thumbnail: '/general/aothungaunau.jpg',
        price: 139000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
    {
        id: 'newproduct2',
        name: 'Áo Dây Mặt Trăng',
        thumbnail: '/general/aodaymattrang.jpg',
        price: 105000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
    {
        id: 'newproduct3',
        name: 'Đầm Hoa Cột Nơ Eo',
        thumbnail: '/general/damhoa.jpg',
        price: 270000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: false,
    },
    {
        id: 'newproduct4',
        name: 'Sơ Mi Kiểu',
        thumbnail: '/general/aosomikieu.jpg',
        price: 205000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: false,
    },
    {
        id: 'newproduct5',
        name: 'Áo Khoác Len',
        thumbnail: '/general/aokhaclen.jpg',
        price: 160000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
]

export const hotProducts = [
    {
        id: 'hotproduct1',
        name: 'Quần baggy',
        thumbnail: '/general/quanbaggy.jpg',
        price: 190000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
    {
        id: 'hotproduct2',
        name: 'Sơ mi cổ vest trái dứa',
        thumbnail: '/general/somicovest.jpg',
        price: 165000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
    {
        id: 'hotproduct3',
        name: 'Wool Coats',
        thumbnail: '/general/woolcoats.jpg',
        price: 120000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
    {
        id: 'hotproduct4',
        name: 'Cotton Baggy Trousers',
        thumbnail: '/general/cottonbaggy.jpg',
        price: 205000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: false,
    },
    {
        id: 'hotproduct5',
        name: 'Sơ mi truyền thống',
        thumbnail: '/general/somitruyenthong.jpg',
        price: 165000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
]

export const newImports = [
    {
        id: 'newimport1',
        name: 'Baggy Jeans',
        thumbnail: '/general/baggyjeans.jpg',
        price: 190000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
    {
        id: 'newimport2',
        name: 'Áo Khoác Len',
        thumbnail: '/general/aokhoaclen.jpg',
        price: 190000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
    {
        id: 'newimport3',
        name: 'Sơ Mi Caro Dệt Nổi',
        thumbnail: '/general/somicaro.jpg',
        price: 240000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: false,
    },
    {
        id: 'newimport4',
        name: 'Linen Shirt',
        thumbnail: '/general/linenshirt.jpg',
        price: 195000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
    {
        id: 'newimport5',
        name: 'Edging Jacket',
        thumbnail: '/general/edging.jpg',
        price: 160000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
]

export const somis = [
    {
        id: 'somi1',
        name: 'Back To School Shirt',
        thumbnail: '/somi/backtoschool.jpg',
        price: 190000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
    {
        id: 'somi2',
        name: 'Sơ Mi Caro',
        thumbnail: '/somi/caro.jpg',
        price: 190000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
    {
        id: 'somi3',
        name: 'Casso Shirt',
        thumbnail: '/somi/casso.jpg',
        price: 240000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: false,
    },
    {
        id: 'somi4',
        name: 'Ciel Shirt',
        thumbnail: '/somi/ciel.jpg',
        price: 195000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
    {
        id: 'somi5',
        name: 'Classic Shirt',
        thumbnail: '/somi/classic.jpg',
        price: 160000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
    {
        id: 'somi6',
        name: 'Sơ Mi Cổ Vest',
        thumbnail: '/somi/covest.jpg',
        price: 190000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
    {
        id: 'somi7',
        name: 'Sơ Mi Caro Dệt Nổi',
        thumbnail: '/somi/detnoi.jpg',
        price: 190000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
    {
        id: 'somi8',
        name: 'Edging Shirt',
        thumbnail: '/somi/edging.jpg',
        price: 240000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: false,
    },
    {
        id: 'somi9',
        name: 'Elena Shirt',
        thumbnail: '/somi/elena.jpg',
        price: 195000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
    {
        id: 'somi10',
        name: 'Sơ Mi Thêu Hoạ Tiết',
        thumbnail: '/somi/hoatiet.jpg',
        price: 160000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
    {
        id: 'newimport11',
        name: 'Sơ Mi Kiểu',
        thumbnail: '/somi/kieu.jpg',
        price: 190000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
    {
        id: 'newimport12',
        name: 'Layla Shirt',
        thumbnail: '/somi/layla.jpg',
        price: 190000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
    {
        id: 'newimport13',
        name: 'Linen Shirt',
        thumbnail: '/somi/linenshirt.jpg',
        price: 240000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: false,
    },
    {
        id: 'newimport14',
        name: 'Sơ Mi Lụa',
        thumbnail: '/somi/lua.jpg',
        price: 195000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
    {
        id: 'newimport15',
        name: 'Sơ Mi Lụa Tay Kiểu',
        thumbnail: '/somi/luataykieu.jpg',
        price: 160000,
        sizes: [
            { name: 'S', soldOut: false },
            { name: 'M', soldOut: true },
            { name: 'L', soldOut: false },
        ],
        soldOut: true,
    },
]
